apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  namespace: nonprod
spec:
  selector:
    app: pythonapp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30102
    protocol: TCP