  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  namespace: prod
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: ecemozer/pythonapp:v$DOCKER_BUILD_NUMBER
        ports:
        - containerPort: 5000